### ISSUE TITLE
Headers lack include guards

### ISSUE THREAD

**Issue by RealKC** [Frederikam/kaiju#1]
# What are include guards?

Include guards are a mechanism used to prevent defining something multiple which happens because the preprocessor is dumb and just pastes the contents of the included files in the file that includes them.
Include guards look like
```c
#ifndef UNIQUE_IDENTIFIER_FOR_YOUR_FILE
#define UNIQUE_IDENTIFIER_FOR_YOUR_FILE
@@contents of header@@
#endif
```
or like
```c
#pragma once
```
The latter is a nonstandard yet very popular extension extension that serves the same purpose as the former. (Clang, GCC, and ICC all support it and those are the main 3 compilers you should concern yourself on Linux)

**Note:** If you go with the first route, you should follow the rules of naming macros, that is:
* they should be UPPER_SNAKE_CASE as to not conflict with other things
* they should not start with _ or contain __ as symbols that look like `_Ugly` and `__ugly` are reserved by the C standard for the implementation.

# What can blow up if I don't have include guards?
You'll sooner or later get errors about symbols being defined multiple times.

# Which headers need them?
From a quick glance, all but bridge.h

**Comment by freyacodes** [comment]
Are there any reason why I should not use `#pragma once`?

This is (practically) not a library, so compiler compatibility is not important.

**Comment by RealKC** [comment]
I don't believe so.
